title: "my first website blog page"
name: "ahmed dauda"
twitter: "@Addataingight"
facebook: "Ahmed Dauda AD"
author: "Ahmed Dauda"
description: "my website where we extract insights from data"
markdown: "krandown"
theme: "minima"
