title: "my first website blog page"
name: "ahmed dauda"
twitter: "https://twitter.com/ADatainsight"
facebook: "Ahmed Dauda AD"
author: "Ahmed Dauda"
email: "addatainsight@gmail.com"
description: "my website where we extract insights from data"
markdown: "krandown"
theme: "minima"
